---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: build-pipelinerun-
  annotations:
    pipelinesascode.tekton.dev/state: started
    pipelinesascode.tekton.dev/source-branch: STONEINTG-1215
    pipelinesascode.tekton.dev/repo-url: 'https://github.com/konflux-ci/integration-service'
    pipelinesascode.tekton.dev/sha-title: 'feat(STONEINTG-1215): new serviceaccount for integration pipelineRuns'
    results.tekton.dev/recordSummaryAnnotations: '{"repo":"integration-service","commit":"9608a898e476234abb711986eef7ee2a59c69485","eventType":"retest-all-comment","pull_request-id":1144}'
    pipelinesascode.tekton.dev/sender: dirgim
    pipelinesascode.tekton.dev/git-auth-secret: pac-gitauth-ujjfku
    build.appstudio.openshift.io/repo: 'https://github.com/konflux-ci/integration-service?rev=9608a898e476234abb711986eef7ee2a59c69485'
    pipelinesascode.tekton.dev/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret", "gRepo": "pipelines-as-code"}'
    pipelinesascode.tekton.dev/check-run-id: '45358961983'
    pipelinesascode.tekton.dev/branch: main
    test.appstudio.openshift.io/pr-group: STONEINTG-1215
    pipelinesascode.tekton.dev/log-url: 'https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/rhtap-integration-tenant/pipelinerun/integration-service-on-pull-request-qd9td'
    build.appstudio.redhat.com/target_branch: main
    pipelinesascode.tekton.dev/url-org: konflux-ci
    pipelinesascode.tekton.dev/source-repo-url: 'https://github.com/dirgim/integration-service'
    pipelinesascode.tekton.dev/max-keep-runs: '3'
    pipelinesascode.tekton.dev/original-prname: integration-service-on-pull-request
    build.appstudio.redhat.com/pull_request_number: '1144'
    pipelinesascode.tekton.dev/pull-request: '1144'
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main"
    pipelinesascode.tekton.dev/url-repository: integration-service
    test.appstudio.openshift.io/snapshot-creation-report: BuildPLRInProgress
    pipelinesascode.tekton.dev/repository: integration-service
    pipelinesascode.tekton.dev/sha: 9608a898e476234abb711986eef7ee2a59c69485
    pipelinesascode.tekton.dev/sha-url: 'https://github.com/konflux-ci/integration-service/commit/9608a898e476234abb711986eef7ee2a59c69485'
    pipelinesascode.tekton.dev/git-provider: github
    pipelinesascode.tekton.dev/installation-id: '47345373'
    pipelinesascode.tekton.dev/event-type: retest-all-comment
    build.appstudio.redhat.com/commit_sha: 9608a898e476234abb711986eef7ee2a59c69485

    chains.tekton.dev/signed: "true"
  labels:
    pipelinesascode.tekton.dev/state: started
    appstudio.openshift.io/component: component-sample
    app.kubernetes.io/version: v0.35.1
    tekton.dev/pipeline: integration-service-on-pull-request-qd9td
    app.kubernetes.io/managed-by: pipelinesascode.tekton.dev
    pipelinesascode.tekton.dev/check-run-id: '45358961983'
    test.appstudio.openshift.io/pr-group-sha: 860739fa6cf5bca035535adcc5313f7350ee0d0df4616d3d466566ec78acb7
    appstudio.openshift.io/application: integration-service
    pipelinesascode.tekton.dev/url-org: konflux-ci
    pipelinesascode.tekton.dev/original-prname: integration-service-on-pull-request
    pipelinesascode.tekton.dev/pull-request: '1144'
    pipelines.appstudio.openshift.io/type: build
    pipelinesascode.tekton.dev/url-repository: integration-service
    pipelinesascode.tekton.dev/repository: integration-service
    pipelinesascode.tekton.dev/sha: 9608a898e476234abb711986eef7ee2a59c69485
    pipelinesascode.tekton.dev/event-type: retest-all-comment

spec:
  pipelineRef:
    resolver: bundles
    params:
      - name: bundle
        value: quay.io/redhat-appstudio/example-tekton-bundle:build-pipeline-pass
      - name: name
        value: build-pipeline-pass
      - name: kind
        value: pipeline
  params:
    - name: output-image
      value: "quay.io/redhat-appstudio/sample-image"
    - name: git-url
      value: "https://github.com/konflux-ci/integration-examples"
    - name: revision
      value: "65cee801fcffa9c1de0be101cfbdd4577ed0da53"
