---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-pipelinerun-
  annotations:
    "appstudio.redhat.com/updateComponentOnSuccess": "false"
    chains.tekton.dev/signed: "true"
  labels:
    pipelines.appstudio.openshift.io/type: "build"
    pipelines.openshift.io/used-by: "build-cloud"
    pipelines.openshift.io/runtime: "nodejs"
    pipelines.openshift.io/strategy: "s2i"
    appstudio.openshift.io/component: "component-sample"
spec:
  pipelineRef:
    name: build-pipeline-pass
    bundle: quay.io/redhat-appstudio/example-tekton-bundle:build-pipeline-pass
  params:
    - name: output-image
      value: "quay.io/redhat-appstudio/sample-image"
    - name: image-digest
      value: "sha256:33d9e33ecc2a2910f967fc2e95f8a64872e9d1e31d00f763a442a8866b391b6c"