apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: test-output
spec:
  results:
    - name: TEST_OUTPUT
      description: Test output
  params:
    - default: "SUCCESS"
      name: RESULT
      description: Test result to be generated
  steps:
    - image: quay.io/redhat-user-workloads-stage/kpavic-tenant/dirgims-the-mentalist-quiz@sha256:256cc5ddda1721825f44e080904415d1219b3b0218866369ec6547aed12c979f