apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-pipeline-pass
spec:
  params:
  - description: 'Fully Qualified Output Image'
    name: output-image
    type: string
  - description: 'Image digest (optional)'
    default: ""
    name: image-digest
    type: string
  results:
    - name: IMAGE_URL
      value: "$(tasks.build-container.results.IMAGE_URL)"
    - name: IMAGE_DIGEST
      value: "$(tasks.build-container.results.IMAGE_DIGEST)"
    - name: CHAINS-GIT_URL
      value: "$(tasks.clone-repository.results.url)"
    - name: CHAINS-GIT_COMMIT
      value: "$(tasks.clone-repository.results.commit)"
  tasks:
    - name: build-container
      taskRef:
        resolver: bundles
        params:
          - name: bundle
            value: quay.io/redhat-appstudio/example-tekton-bundle:build-container
          - name: name
            value: build-container
          - name: kind
            value: task
      params:
        - name: image-url
          value: "$(params.output-image)"
        - name: image-digest
          value: "$(params.image-digest)"
    - name: clone-repository
      taskRef:
        resolver: bundles
        params:
          - name: bundle
            value: quay.io/redhat-appstudio/example-tekton-bundle:clone-repository
          - name: name
            value: clone-repository
          - name: kind
            value: task
