apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: integration-pipeline-pass
spec:
  tasks:
    - name: task-success
      taskRef:
        resolver: bundles
        params:
          - name: bundle
            value: quay.io/redhat-appstudio/example-tekton-bundle:test-output
          - name: name
            value: test-output
          - name: kind
            value: task
      params:
        - name: RESULT
          value: SUCCESS
    - name: task-success-2
      taskRef:
        resolver: bundles
        params:
          - name: bundle
            value: quay.io/redhat-appstudio/example-tekton-bundle:test-output
          - name: name
            value: test-output
          - name: kind
            value: task
      params:
        - name: RESULT
          value: SUCCESS
    - name: task-skipped
      taskRef:
        resolver: bundles
        params:
          - name: bundle
            value: quay.io/redhat-appstudio/example-tekton-bundle:test-output
          - name: name
            value: test-output
          - name: kind
            value: task
      params:
        - name: RESULT
          value: SKIPPED
