apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: integration-environment-pipeline-pass
spec:
  tasks:
    - name: task-success
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/integration-examples 
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/test_output.yaml
      params:
        - name: RESULT
          value: SUCCESS
    - name: provision-env-with-ephemeral-namespace
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/dirgim/integration-examples
          - name: revision
            value: test-serviceaccount
          - name: pathInRepo
            value: tasks/eaas-provision-space.yaml
      params:
        - name: ownerName
          value: $(context.pipelineRun.name)
        - name: ownerUid
          value: $(context.pipelineRun.uid)
    - name: task-success-2
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/integration-examples 
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/test_output.yaml
      params:
        - name: RESULT
          value: SKIPPED

